### ISSUE TITLE
Make references on entries an array of objects

### ISSUE THREAD

**Issue by tsevdos** [tsevdos/greek-in-tech#3]
Currently, the references on each entry is an array of strings (URLs)

``` json
"references": [
    "https://en.wikipedia.org/wiki/Cron"
  ]
```

It will be much better if it was an array of objects, with `name` and `source` as properties on each reference. 

``` json
"references": [
    {
       "name": "Wikipedia",
       "source": "https://en.wikipedia.org/wiki/Cron"
    }
  ] 
```

**Comment by NekCS** [comment]
Hi @tsevdos , I would like to help you with this issue. I am trying to do a couple contributions in order to get familiar with Git and GitHub and I think that this issue is a great start for me.

**Comment by tsevdos** [comment]
Sure, no problem from my part.
